# Generated by Django 5.0.4 on 2024-06-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='homework_status',
            field=models.BooleanField(default=False),
        ),
    ]
