# Generated by Django 5.0.6 on 2024-06-12 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_homework'),
        ('users', '0013_rename_team_teacher_date_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='users.team'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='users.team'),
        ),
    ]
