# Generated by Django 5.0.6 on 2024-06-12 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_homework_team_alter_lesson_team'),
        ('users', '0013_rename_team_teacher_date_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='users.team'),
        ),
    ]
