# Generated by Django 5.0.4 on 2024-06-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_homework_team'),
        ('users', '0013_rename_team_teacher_date_of'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homework',
            unique_together={('student', 'team')},
        ),
    ]
