# Generated by Django 5.0.4 on 2024-08-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_davomat_team_alter_lesson_homework_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='homework_file',
            new_name='lesson_file',
        ),
    ]
