# Generated by Django 5.0.4 on 2024-09-03 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_date_remove_davomat_data_davomat_date'),
        ('users', '0013_rename_team_teacher_date_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='davomat',
            name='team',
        ),
        migrations.AddField(
            model_name='date',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='users.team'),
        ),
    ]
