# Generated by Django 5.0.4 on 2024-09-07 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_remove_davomat_team_date_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davomat',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='students.date'),
        ),
    ]
