# Generated by Django 5.0.4 on 2024-09-07 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_alter_davomat_date'),
        ('users', '0013_rename_team_teacher_date_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='davomat',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamsa', to='users.team'),
        ),
    ]
