# Generated by Django 5.0.4 on 2024-09-10 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_davomat_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='homework_file',
        ),
        migrations.CreateModel(
            name='Homeworkfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_file', models.FileField(blank=True, null=True, upload_to='homeworks')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.homework')),
            ],
        ),
    ]
