# Generated by Django 5.0.4 on 2024-09-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_remove_homework_homework_file_homeworkfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='homework_file',
            field=models.FileField(blank=True, null=True, upload_to='homeworks'),
        ),
        migrations.DeleteModel(
            name='Homeworkfile',
        ),
    ]
