# Generated by Django 5.1.1 on 2024-09-20 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_homework_homework_file_delete_homeworkfile'),
        ('users', '0013_rename_team_teacher_date_of'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homework',
            unique_together={('lesson', 'student')},
        ),
    ]
