# Generated by Django 5.0.4 on 2024-08-31 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0013_rename_team_teacher_date_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oylik', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolov_set', to='users.student')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolov_set', to='users.team')),
            ],
        ),
    ]
