# Generated by Django 5.0.4 on 2024-08-31 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('users', '0013_rename_team_teacher_date_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tolov',
            name='student',
        ),
        migrations.RemoveField(
            model_name='tolov',
            name='team',
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=150)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolov_set', to='users.student')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolov_set', to='users.team')),
            ],
        ),
        migrations.AddField(
            model_name='tolov',
            name='month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tolov_set', to='teachers.month'),
            preserve_default=False,
        ),
    ]
