# Generated by Django 5.0.4 on 2024-08-31 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_remove_tolov_student_remove_tolov_team_month_and_more'),
        ('users', '0013_rename_team_teacher_date_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='student',
        ),
        migrations.AddField(
            model_name='tolov',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tolov_set', to='users.student'),
            preserve_default=False,
        ),
    ]
