# Generated by Django 5.0.4 on 2024-09-03 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_remove_month_student_tolov_student'),
        ('users', '0013_rename_team_teacher_date_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolov',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tolov_set', to='users.student'),
        ),
    ]
